apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.prefix }}-ops
  namespace: {{ .Values.app.namespace }}
spec:
  type: NodePort
  ports:
  - name: jenkins
    port: 8080
    targetPort: 8080
    nodePort: 30080
  # - name: nexus
  #   port: 8081
  #   targetPort: 8081
  #   nodePort: 30081
  # - name: sonarqube
  #   port: 9000
  #   targetPort: 9000
  #   nodePort: 30900
  selector:
    app: {{ .Values.app.prefix }}-ops
