/*
 * Template group dev_ops_deployment_yaml
 * Compiled on Wed Mar 20 2019 14:54:31 GMT+0530 (India Standard Time)
 */
var path = require("path");
var base = path.dirname(module.filename);

function getInstance(st, group) {
    "use strict";
var r;
var gFile = "dev_ops_deployment_yaml"; 

group.name = "dev_ops_deployment_yaml";





//
// Template /dev_ops_deployment_yaml
//
r = function(w, rc) {
    var g = this.owningGroup,
        s = this.scope;
    
    w.write("apiVersion: extensions/v1beta1");
    w.write("\n");
    w.write("kind: Deployment");
    w.write("\n");
    w.write("metadata:");
    w.write("\n");
    w.pushIndentation("  ");
    w.write("name: ");
    w.popIndentation();
    st.write(w, s, g, rc, s.project_name);
    w.write("-dev-ops");
    w.write("\n");
    w.pushIndentation("  ");
    w.write("namespace: ");
    w.popIndentation();
    st.write(w, s, g, rc, s.project_name);
    w.write("\n");
    w.write("spec:");
    w.write("\n");
    w.pushIndentation("  ");
    w.write("replicas: 1");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("template:");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("metadata:");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("labels:");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("app: ");
    w.popIndentation();
    st.write(w, s, g, rc, s.project_name);
    w.write("-dev-ops");
    w.write("\n");
    w.pushIndentation("    ");
    w.write("spec:");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("containers:");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("- name: jenkins-container");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("imagePullPolicy: Always");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("image: tharanirajan/gep-jenkins:1.0");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("env:");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("- name: JAVA_OPTS");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("value: -Djenkins.install.runSetupWizard=true");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("ports:");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("- name: http-port");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("containerPort: 8080");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("- name: jnlp-port");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("containerPort: 50000");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("volumeMounts:");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("- name: jenkins-data");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("mountPath: /var/jenkins_home             ");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("- name: nexus-container ");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("imagePullPolicy: Always");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("image: sonatype/nexus3 ");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("resources:");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("limits:");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("memory: \"4Gi\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("cpu: \"1000m\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("requests:");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("memory: \"2Gi\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("cpu: \"500m\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("ports:");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("- name: http-port");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("containerPort: 8081");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("volumeMounts:");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("- name: nexus-data");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("mountPath: /nexus-data");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("- name: sonarqube-container");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("image: sonarqube:latest");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("args:");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("- -Dsonar.web.context=/");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("env:");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("- name: SONARQUBE_JDBC_PASSWORD");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("value: ");
    w.popIndentation();
    st.write(w, s, g, rc, s.project_name);
    w.write("\n");
    w.pushIndentation("            ");
    w.write("- name: SONARQUBE_JDBC_URL");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("value: jdbc:postgresql://");
    w.popIndentation();
    st.write(w, s, g, rc, s.project_name);
    w.write("-dev-ops-db:5432/sonar");
    w.write("\n");
    w.pushIndentation("          ");
    w.write("ports:");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("- containerPort: 9000");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("name: sonarqube                                ");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("volumes:");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("- name: jenkins-data");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("emptyDir: {}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("- name: nexus-data");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("emptyDir: {}  ");
    w.popIndentation();
};
r.args = [
        { name: "project_name"     }
];
group.addTemplate("/dev_ops_deployment_yaml", r); 


return group;
}
getInstance.base = base;

module.exports = getInstance;