/*
 * Template group gcam_resource
 * Compiled on Wed Dec 08 2021 14:37:18 GMT+0530 (India Standard Time)
 */
var path = require("path");
var base = path.dirname(module.filename);

function getInstance(st, group) {
    "use strict";
var r;
var gFile = "gcam_resource"; 

group.name = "gcam_resource";





//
// Template /gcam_resource
//
r = function(w, rc) {
    var g = this.owningGroup,
        s = this.scope;
    
    w.write("\n");
    w.write("export const resourcetypes = [");
    w.write("\n");
    w.pushIndentation("  ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"resource_name\": \"manageroles\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"resource_type\": \"screen\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"components\": [{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"label_1425\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"878979\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"textbox_6272\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"135979\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"label_2437\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"343979\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"dropdown_73821\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"738291\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"resource_name\": \"home\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"resource_type\": \"screen\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"user\", \"admin");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"components\": [{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"label_1425\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"878979\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"textbox_6272\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"135979\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"label_2437\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"343979\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"dropdown_73821\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"738291\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"resource_name\": \"manageusers\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"resource_type\": \"screen\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"components\": [{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"label_1425\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"878979\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"textbox_6272\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"135979\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"label_2437\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"343979\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"dropdown_73821\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"738291\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"resource_name\": \"admin\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"resource_type\": \"screen\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"components\": [{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"label_1425\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"878979\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"textbox_6272\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"135979\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"label_2437\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"343979\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"dropdown_73821\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"738291\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("       ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"resource_name\": \"sefscreen\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"resource_type\": \"screen\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"admin\",\"user\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"components\": [{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"label_1425\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"878979\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"textbox_6272\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"135979\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"label_2437\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"343979\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"dropdown_73821\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"738291\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"resource_name\": \"authorization\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"resource_type\": \"screen\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"components\": [{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"label_1425\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"878979\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"textbox_6272\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"135979\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"label_2437\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"343979\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"dropdown_73821\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"738291\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"resource_name\": \"landing\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"resource_type\": \"screen\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"guest\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"components\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"login\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"id\": \"878979\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"admin\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"user\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"guest\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"signup\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"id\": \"135979\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"admin\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"user\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"guest\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.write("    ");
    if (st.test(s.object)) {
    
        st.write(w, s, g, rc, (function() {
        var tp = [],
        attr = s.object;
        tp.push(st.makeSubTemplate(g, function(w, rc) {
            var g = this.owningGroup,
            s = this.scope;
            
                     w.write("\"resource_name\": \"");
                     st.write(w, s, g, rc, st.prop(s, g, rc, s.value, "resources", { file: gFile, line: 261, column: 29 }));
                     w.write("\",");
                     w.write("\n");
                     w.pushIndentation("    ");
                     w.write("\"resource_type\": \"screen\",");
                     w.popIndentation();
                     w.write("\n");
                     w.pushIndentation("    ");
                     w.write("\"roles\": [");
                     w.popIndentation();
                     w.write("\n");
                     w.pushIndentation("      ");
                     w.write("\"admin\", \"");
                     w.popIndentation();
                     st.write(w, s, g, rc, st.prop(s, g, rc, s.value, "role", { file: gFile, line: 264, column: 23 }));
                     w.write("\"");
                     w.write("\n");
                     w.pushIndentation("    ");
                     w.write("],");
                     w.popIndentation();
                     w.write("\n");
                     w.write("    ");
            }, [
            { name: "value"     }
            ])); 
        return st.map(attr, tp);
        })(), {separator: "\n"});
    
    
    }
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"components\": [{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"label_1425\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"878979\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"textbox_6272\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"135979\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"label_2437\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"343979\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"dropdown_73821\":");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"id\": \"738291\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"roles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"admin\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\n");
    w.popIndentation();
    w.write("]");
    w.write("\n");
};
r.args = [
        { name: "object"     }
];
group.addTemplate("/gcam_resource", r); 


return group;
}
getInstance.base = base;

module.exports = getInstance;