apiVersion: v1
kind: Service
metadata:
  name: gep-dev-telemetry
  namespace: gep-dev-201902
  labels:
    app: gep-dev-telemetry
spec:
  type: NodePort
  ports:
    - name: vault
      targetPort: 8200
      port: 8200
      nodePort: 30082 
    - name: prometheus
      targetPort: 9090
      port: 9090
      nodePort: 30090  
  selector:
    app: gep-dev-telemetry
