kind: PersistentVolume
apiVersion: v1
metadata:
  name: gep-dev-app-mongo-data-pv
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongo/
