apiVersion: v1
kind: Service
metadata:
  name: gep-dev-app
  namespace: gep-dev-201902
spec:
  type: LoadBalancer
  ports:
  - name: node-app
    port: 3000
    targetPort: 3000
  selector:
    app: gep-dev-app
