apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.app.prefix }}-system-entry
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.app.prefix }}-system-entry
    spec:
      containers:
        - name: {{ .Values.deployment.systementry.name }}-container
          imagePullPolicy: {{ .Values.deployment.customImagePullPolicy }}
          image: {{ .Values.deployment.systementry.image }}
          ports:
            - name: http-port
              containerPort: 80
        - name: {{ .Values.deployment.apigateway.name }}-container
          imagePullPolicy: {{ .Values.deployment.customImagePullPolicy }}
          image: {{ .Values.deployment.apigateway.image }}
          ports:
            - name: http-port
              containerPort: 3000

