/*
 * Template group connector_admin_css
 * Compiled on Fri May 21 2021 21:15:50 GMT+0530 (India Standard Time)
 */
var path = require("path");
var base = path.dirname(module.filename);

function getInstance(st, group) {
    "use strict";
var r;
var gFile = "connector_admin_css"; 

group.name = "connector_admin_css";





//
// Template /connector_admin_css
//
r = function(w, rc) {
    var g = this.owningGroup,
        s = this.scope;
    
    w.pushIndentation("    ");
    w.write("table.table-bordered {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("border: 1px solid black;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("margin-top: 20px;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("text-align: left;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("table-layout: auto;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("color: black;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("background-color: white;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\n");
    w.popIndentation();
    w.pushIndentation("  ");
    w.write("table.table-bordered>thead>tr>th {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("border: 1px solid black;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("color: black;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("background-color: darkgrey;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\n");
    w.popIndentation();
    w.pushIndentation("  ");
    w.write("table.table-bordered>tbody>tr>td {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("border: 1px solid black;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\n");
    w.popIndentation();
    w.pushIndentation("  ");
    w.write("* {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("box-sizing: border-box;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\n");
    w.popIndentation();
    w.pushIndentation("  ");
    w.write("body {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("margin: 0;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\n");
    w.popIndentation();
    w.pushIndentation("  ");
    w.write(".row {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("display: table;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("padding-top: 10px;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("padding-right: 10px;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("padding-bottom: 10px;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("padding-left: 10px;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("width: 100%;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\n");
    w.popIndentation();
    w.pushIndentation("  ");
    w.write(".cell {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("width: 8%;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("display: table-cell;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("height: 75px;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\n");
    w.popIndentation();
    w.pushIndentation("  ");
    w.write("#template-im4h {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("margin: 0 0 0 0;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\n");
    w.popIndentation();
    w.pushIndentation("  ");
    w.write("#template-itih {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("width: 514px;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("padding: 10px 10px 10px 10px;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\n");
    w.popIndentation();
    w.pushIndentation("  ");
    w.write("#template-ivnj {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("margin: 0 0 0 0;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\n");
    w.popIndentation();
    w.pushIndentation("  ");
    w.write("#template-ikqf {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("width: 514px;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("padding: 10px 10px 10px 10px;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\n");
    w.popIndentation();
    w.pushIndentation("  ");
    w.write("#template-i29p {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("margin: 0 0 0 0;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\n");
    w.popIndentation();
    w.pushIndentation("  ");
    w.write("#template-ilqq {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("width: 514px;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("padding: 10px 10px 10px 10px;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\n");
    w.popIndentation();
    w.pushIndentation("  ");
    w.write("#template-immc {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("margin: 0 0 0 0;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\n");
    w.popIndentation();
    w.pushIndentation("  ");
    w.write("#template-ivcj {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("width: 514px;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("padding: 10px 10px 10px 10px;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\n");
    w.popIndentation();
    w.pushIndentation("  ");
    w.write("#template-iba4 {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("margin: 0 0 0 0;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\n");
    w.popIndentation();
    w.pushIndentation("  ");
    w.write("#template-iiohv {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("width: 514px;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("padding: 10px 10px 10px 10px;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\n");
    w.popIndentation();
    w.pushIndentation("  ");
    w.write(".label {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("color: #000000;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("text-transform: capitalize;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("font-size: 14px;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("padding: 2.1px 6.3px 3.15px 1px;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\n");
    w.popIndentation();
    w.pushIndentation("  ");
    w.write(".input.form-control {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("margin: 5px 0 0 0;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\n");
    w.popIndentation();
    w.pushIndentation("  ");
    w.write(".align-right {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("float: right;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("margin-top: -26px;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("margin-right: 10px;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\n");
    w.popIndentation();
    w.pushIndentation("  ");
    w.write(".invalid-feedback {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("display: unset !important;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("width: 100%;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("margin-top: 0.25rem;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("font-size: 90%;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("font-weight: bold;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("color: #dc3545;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\n");
    w.popIndentation();
    w.pushIndentation("  ");
    w.write("#template-ibfdk {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("background-color: #024174;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("color: white;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\n");
    w.popIndentation();
    w.pushIndentation("  ");
    w.write("#template-i8s2n {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("margin-left: 20px;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("background-color: grey;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("color: white;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\n");
    w.popIndentation();
    w.pushIndentation("  ");
    w.write("@media (max-width: 768px) {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write(".cell {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("width: 100%;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("display: block;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("}");
    w.popIndentation();
};
r.args = [
        { name: "html"     }
];
group.addTemplate("/connector_admin_css", r); 


return group;
}
getInstance.base = base;

module.exports = getInstance;