apiVersion: v1
kind: Service
metadata:
 labels:
   name: {{ .Values.app.prefix }}-app-db
 name: {{ .Values.app.prefix }}-app-db
 namespace: {{ .Values.app.namespace }}
spec:
 type: {{ .Values.service.type }}
 ports:
 - name: {{ .Values.service.mongo.name }}-db
   port: {{ .Values.service.mongo.port }}
   targetPort: {{ .Values.service.mongo.targetPort }}
   nodePort: {{ .Values.service.mongo.nodePort }}
 selector:
   name: {{ .Values.app.prefix }}-app-db
