apiVersion: v1
kind: Service
metadata:
  name: gep-dev-system-entry
  namespace: gep-dev-201902
spec:
  type: NodePort
  ports:
  - name: nginx-app
    port: 80
    targetPort: 80
    nodePort: 30000
  - name: apigateway-app
    port: 3000
    targetPort: 3000
    nodePort: 30001
  selector:
    app: gep-dev-system-entry
