apiVersion: v1
kind: Service
metadata:
  name: gep-dev-system-entry
  namespace: gep-dev-201902
spec:
  type: LoadBalancer
  ports:
  - name: nginx-app
    port: 80
    targetPort: 80
  selector:
    app: gep-dev-system-entry
