apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gep-dev-system-entry
  namespace: gep-dev-201902
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gep-dev-system-entry
    spec:
      containers:
        - name: nginx-container
          imagePullPolicy: Always
          image: tharanirajan/gep-dev-appbuilder:1.0
          ports:
            - name: http-port
              containerPort: 80
        - name: apigateway-container
          imagePullPolicy: Always
          image: tharanirajan/gep-dev-apigateway:1.0
          ports:
            - name: http-port
              containerPort: 3000

