/*
 * Template group build_script
 * Compiled on Fri Jul 19 2019 11:15:33 GMT+0530 (India Standard Time)
 */
var path = require("path");
var base = path.dirname(module.filename);

function getInstance(st, group) {
    "use strict";
var r;
var gFile = "build_script"; 

group.name = "build_script";





//
// Template /build_script
//
r = function(w, rc) {
    var g = this.owningGroup,
        s = this.scope;
    
    w.write("#!bin/bash");
    w.write("\n");
    w.write("\n");
    w.write("APIGATEWAYCODE='../../application/services/apigateway/'");
    w.write("\n");
    w.write("APIGATEWAYIMAGENAME='");
    st.write(w, s, g, rc, s.project_name);
    w.write("-apigateway:1.0'");
    w.write("\n");
    w.write("\n");
    w.write("CAMUNDACODE='../camunda/'");
    w.write("\n");
    w.write("CAMUNDAIMAGENAME='");
    st.write(w, s, g, rc, s.project_name);
    w.write("-camunda:1.0'");
    w.write("\n");
    w.write("\n");
    w.write("AUTHPROXYCODE='../authproxy/'");
    w.write("\n");
    w.write("AUTHPROXYIMAGENAME='");
    st.write(w, s, g, rc, s.project_name);
    w.write("-authproxy:1.0'");
    w.write("\n");
    w.write("\n");
    w.write("SECURITYCODE='../securitymanager/'");
    w.write("\n");
    w.write("SECURITYIMAGENAME='");
    st.write(w, s, g, rc, s.project_name);
    w.write("-security:1.0'");
    w.write("\n");
    w.write("\n");
    w.write("DESKTOPCODE='../../client/desktop/");
    st.write(w, s, g, rc, s.project_name);
    w.write("/'");
    w.write("\n");
    w.write("DESKTOPIMAGENAME='");
    st.write(w, s, g, rc, s.project_name);
    w.write("-desktop:1.0'");
    w.write("\n");
    w.write("\n");
    w.write("echo \"Started to build docker images for pod....\"");
    w.write("\n");
    w.write("\n");
    w.write("build_apigateway_image () {");
    w.write("\n");
    w.write("\n");
    w.write("cd $APIGATEWAYCODE");
    w.write("\n");
    w.write("docker build -t $APIGATEWAYIMAGENAME .");
    w.write("\n");
    w.write("if [ $? -eq 0 ]; then");
    w.write("\n");
    w.pushIndentation("    ");
    w.write("echo \"image ");
    w.popIndentation();
    st.write(w, s, g, rc, s.project_name);
    w.write("-apigateway:1.0 build successfully loading into kind it take a while...\"");
    w.write("\n");
    w.pushIndentation("    ");
    w.write("kind load docker-image $APIGATEWAYIMAGENAME");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("echo \"$APIGATEWAYIMAGENAME is successfully loaded into kind\"");
    w.popIndentation();
    w.write("\n");
    w.write("else");
    w.write("\n");
    w.pushIndentation("    ");
    w.write("echo \"image ");
    w.popIndentation();
    st.write(w, s, g, rc, s.project_name);
    w.write("-apigateway:1.0 build failed\"");
    w.write("\n");
    w.write("fi");
    w.write("\n");
    w.write("\n");
    w.write("}");
    w.write("\n");
    w.write("\n");
    w.write("build_camunda_image () {");
    w.write("\n");
    w.write("\n");
    w.write("cd $CAMUNDACODE");
    w.write("\n");
    w.write("docker build -t $CAMUNDAIMAGENAME .");
    w.write("\n");
    w.write("if [ $? -eq 0 ]; then");
    w.write("\n");
    w.pushIndentation("    ");
    w.write("echo \"image ");
    w.popIndentation();
    st.write(w, s, g, rc, s.project_name);
    w.write("-camunda:1.0 build successfully loading into kind it take a while...\"");
    w.write("\n");
    w.pushIndentation("    ");
    w.write("kind load docker-image $CAMUNDAIMAGENAME");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("echo \"$CAMUNDAIMAGENAME is successfully loaded into kind\"");
    w.popIndentation();
    w.write("\n");
    w.write("else");
    w.write("\n");
    w.pushIndentation("    ");
    w.write("echo \"image ");
    w.popIndentation();
    st.write(w, s, g, rc, s.project_name);
    w.write("-camunda:1.0 build failed\"");
    w.write("\n");
    w.write("fi");
    w.write("\n");
    w.write("\n");
    w.write("}");
    w.write("\n");
    w.write("\n");
    w.write("build_authproxy_image () {");
    w.write("\n");
    w.write("\n");
    w.write("cd $AUTHPROXYCODE");
    w.write("\n");
    w.write("docker build -t $AUTHPROXYIMAGENAME .");
    w.write("\n");
    w.write("if [ $? -eq 0 ]; then");
    w.write("\n");
    w.pushIndentation("    ");
    w.write("echo \"image ");
    w.popIndentation();
    st.write(w, s, g, rc, s.project_name);
    w.write("-authproxy:1.0 build successfully loading into kind it take a while...\"");
    w.write("\n");
    w.pushIndentation("    ");
    w.write("kind load docker-image $AUTHPROXYIMAGENAME");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("echo \"$AUTHPROXYIMAGENAME is successfully loaded into kind\"");
    w.popIndentation();
    w.write("\n");
    w.write("else");
    w.write("\n");
    w.pushIndentation("    ");
    w.write("echo \"image ");
    w.popIndentation();
    st.write(w, s, g, rc, s.project_name);
    w.write("-authproxy:1.0 build failed\"");
    w.write("\n");
    w.write("fi");
    w.write("\n");
    w.write("\n");
    w.write("}");
    w.write("\n");
    w.write("\n");
    w.write("build_security_image () {");
    w.write("\n");
    w.write("\n");
    w.write("cd $SECURITYCODE");
    w.write("\n");
    w.write("docker build -t $SECURITYIMAGENAME .");
    w.write("\n");
    w.write("if [ $? -eq 0 ]; then");
    w.write("\n");
    w.pushIndentation("    ");
    w.write("echo \"image ");
    w.popIndentation();
    st.write(w, s, g, rc, s.project_name);
    w.write("-security:1.0 build successfully loading into kind it take a while...\"");
    w.write("\n");
    w.pushIndentation("    ");
    w.write("kind load docker-image $SECURITYIMAGENAME");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("echo \"$SECURITYIMAGENAME is successfully loaded into kind\"");
    w.popIndentation();
    w.write("\n");
    w.write("else");
    w.write("\n");
    w.pushIndentation("    ");
    w.write("echo \"image ");
    w.popIndentation();
    st.write(w, s, g, rc, s.project_name);
    w.write("-security:1.0 build failed\"");
    w.write("\n");
    w.write("fi");
    w.write("\n");
    w.write("\n");
    w.write("}");
    w.write("\n");
    w.write("\n");
    w.write("build_appbuilder_image () {");
    w.write("\n");
    w.write("\n");
    w.write("cd $DESKTOPCODE");
    w.write("\n");
    w.write("npm install");
    w.write("\n");
    w.write("ng build");
    w.write("\n");
    w.write("docker build -t $DESKTOPIMAGENAME .");
    w.write("\n");
    w.write("if [ $? -eq 0 ]; then");
    w.write("\n");
    w.pushIndentation("    ");
    w.write("echo \"image ");
    w.popIndentation();
    st.write(w, s, g, rc, s.project_name);
    w.write("-desktop:1.0 build successfully loading into kind it take a while...\"");
    w.write("\n");
    w.pushIndentation("    ");
    w.write("kind load docker-image $DESKTOPIMAGENAME");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("echo \"$DESKTOPIMAGENAME is successfully loaded into kind\"");
    w.popIndentation();
    w.write("\n");
    w.write("else");
    w.write("\n");
    w.pushIndentation("    ");
    w.write("echo \"image ");
    w.popIndentation();
    st.write(w, s, g, rc, s.project_name);
    w.write("-desktop:1.0 build failed\"");
    w.write("\n");
    w.write("fi");
    w.write("\n");
    w.write("\n");
    w.write("}");
    w.write("\n");
    w.write("\n");
    w.write("build_apigateway_image");
    w.write("\n");
    w.write("build_camunda_image");
    w.write("\n");
    w.write("build_authproxy_image");
    w.write("\n");
    w.write("build_security_image");
    w.write("\n");
    w.write("build_appbuilder_image");
    w.write("\n");
};
r.args = [
        { name: "project_name"     },
{ name: "base_path"     }
];
group.addTemplate("/build_script", r); 


return group;
}
getInstance.base = base;

module.exports = getInstance;