apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.prefix }}-telemetry
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.prefix }}-telemetry
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: vault
      targetPort: 8200
      port: 8200
      nodePort: 30082 
    - name: prometheus
      targetPort: 9090
      port: 9090
      nodePort: 30090  
  selector:
    app: {{ .Values.app.prefix }}-telemetry
