export const UserEntity = {
    name: "User",
    description: "User details",
    project_id: "",
    field: [{
        name: "firstname",
        type_name: "Text",
        data_type: "String",
        description: "user first name",
        is_entity_type: false,
        is_list_type: false,
        list_type: null,
        list_value: null,
        entity_id: null,
    },
    {
        name: "lastname",
        type_name: "Text",
        data_type: "String",
        description: "user last name",
        is_entity_type: false,
        is_list_type: false,
        list_type: null,
        list_value: null,
        entity_id: null,
    }, {
        name: "email",
        type_name: "Text",
        data_type: "String",
        description: "user Email",
        is_entity_type: false,
        is_list_type: false,
        list_type: null,
        list_value: null,
        entity_id: null,
    }, {
        name: "password",
        type_name: "Text",
        data_type: "String",
        description: "user password",
        is_entity_type: false,
        is_list_type: false,
        list_type: null,
        list_value: null,
        entity_id: null,
    }]
}