apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.prefix }}-camunda
  namespace: {{ .Values.app.namespace }}
spec:
  type: NodePort
  ports:
  - name: camunda
    port: 6000
    targetPort: 8080
    nodePort: 30060
  selector:
    app: {{ .Values.app.prefix }}-camunda
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.app.prefix }}-camunda
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.app.prefix }}-camunda
    spec:
      containers:
        - name: camunda-container
          imagePullPolicy: Always
          image: camunda/camunda-bpm-platform
          ports:
            - name: http-port
              containerPort: 8080
