---
openapi: 3.0.0
info:
   version: 1.3.0
   title: myshare open api specification
   description: sharedfeaturesgenmanager API
   termsOfService: http://api_url/terms/
   contact:
      name: ContactName
      email: hello@wolox.co
      url: https://www.wolox.com.ar/
   license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
   - url: http://localhost:8009
     description: sharedfeaturesgenmanager
tags:
- name: gfc
  description: this is the feature config data
paths:
   "/gfc/{id}":
      delete:
         tags:
         -  gfc
         description: GpDelete
         parameters:
         -  in: "path"
            description: GpDelete
            name: id
            required: true
            schema:
               type: "string"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      get:
         tags:
         -  gfc
         description: GpGetNounById
         parameters:
         -  in: "path"
            description: GpGetNounById
            name: id
            required: true
            schema:
               type: "string"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/gfc":
      get:
         tags:
         -  gfc
         description: GpGetAllValues
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      post:
         tags:
         -  gfc
         description: GpCreate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/gfc"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      put:
         tags:
         -  gfc
         description: GpUpdate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/gfc"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/gfc/get/search":
      get:
         tags:
         -  gfc
         description: GpSearch
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/gfc/get/update":
      put:
         tags:
         -  gfc
         description: GpSearchForUpdate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/gfc"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
components:
   schemas:
      gfc:
         type: object
         properties:
            feature-name:
               type: "string"
               description: Description
            sharingvisibilitystatus:
               type: "string"
               description: Description
            type:
               type: "string"
               description: Description
            author-name:
               type: "string"
               description: Description
            datecreated:
               type: "string"
               description: Description
            datemodified:
               type: "string"
               description: Description
            authoremail:
               type: "string"
               description: Description
            organization:
               type: "string"
               description: Description
            iconlocation:
               type: "string"
               description: Description