apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.app.prefix }}-app
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.app.prefix }}-app
    spec:
      containers:
        - name: {{ .Values.deployment.flowmanager.name }}-container
          imagePullPolicy: {{ .Values.deployment.customImagePullPolicy }}
          image: {{ .Values.deployment.flowmanager.image }}
          ports:
            - name: http-port
              containerPort: 3001
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: VAULT_API
              value: "http://{{ .Values.app.prefix }}-telemetry.{{ .Values.app.namespace }}.svc.cluster.local:8200"    
        - name: {{ .Values.deployment.microflowmanager.name }}-container
          imagePullPolicy: {{ .Values.deployment.customImagePullPolicy }}
          image: {{ .Values.deployment.microflowmanager.image }}
          ports:
            - name: http-port
              containerPort: 3002
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: VAULT_API
              value: "http://{{ .Values.app.prefix }}-telemetry.{{ .Values.app.namespace }}.svc.cluster.local:8200"
        - name: {{ .Values.deployment.projectmanager.name }}-container
          imagePullPolicy: {{ .Values.deployment.customImagePullPolicy }}
          image: {{ .Values.deployment.projectmanager.image }}
          ports:
            - name: http-port
              containerPort: 3003
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: VAULT_API
              value: "http://{{ .Values.app.prefix }}-telemetry.{{ .Values.app.namespace }}.svc.cluster.local:8200"
        - name: {{ .Values.deployment.screenmanager.name }}-container
          imagePullPolicy: {{ .Values.deployment.customImagePullPolicy }}
          image: {{ .Values.deployment.screenmanager.image }}
          ports:
            - name: http-port
              containerPort: 3004
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: VAULT_API
              value: "http://{{ .Values.app.prefix }}-telemetry.{{ .Values.app.namespace }}.svc.cluster.local:8200"
        - name: {{ .Values.deployment.entitymanager.name }}-container
          imagePullPolicy: {{ .Values.deployment.customImagePullPolicy }}
          image: {{ .Values.deployment.entitymanager.image }}
          ports:
            - name: http-port
              containerPort: 3005
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: VAULT_API
              value: "http://{{ .Values.app.prefix }}-telemetry.{{ .Values.app.namespace }}.svc.cluster.local:8200"
        - name: {{ .Values.deployment.featuremanager.name }}-container
          imagePullPolicy: {{ .Values.deployment.customImagePullPolicy }}
          image: {{ .Values.deployment.featuremanager.image }}
          ports:
            - name: http-port
              containerPort: 3006
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: VAULT_API
              value: "http://{{ .Values.app.prefix }}-telemetry.{{ .Values.app.namespace }}.svc.cluster.local:8200"
        - name: {{ .Values.deployment.securitymanager.name }}-container
          imagePullPolicy: {{ .Values.deployment.customImagePullPolicy }}
          image: {{ .Values.deployment.securitymanager.image }}
          ports:
            - name: http-port
              containerPort: 3007
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: VAULT_API
              value: "http://{{ .Values.app.prefix }}-telemetry.{{ .Values.app.namespace }}.svc.cluster.local:8200"
        - name: {{ .Values.deployment.camundamanager.name }}-container
          imagePullPolicy: {{ .Values.deployment.customImagePullPolicy }}
          image: {{ .Values.deployment.camundamanager.image }}
          ports:
            - name: http-port
              containerPort: 3008
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: VAULT_API
              value: "http://{{ .Values.app.prefix }}-telemetry.{{ .Values.app.namespace }}.svc.cluster.local:8200"
        - name: {{ .Values.deployment.proxymanager.name }}-container
          imagePullPolicy: {{ .Values.deployment.customImagePullPolicy }}
          image: {{ .Values.deployment.proxymanager.image }}
          ports:
            - name: http-port
              containerPort: 3009
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: VAULT_API
              value: "http://{{ .Values.app.prefix }}-telemetry.{{ .Values.app.namespace }}.svc.cluster.local:8200"
        - name: {{ .Values.deployment.adminmanager.name }}-container
          imagePullPolicy: {{ .Values.deployment.customImagePullPolicy }}
          image: {{ .Values.deployment.adminmanager.image }}
          ports:
            - name: http-port
              containerPort: 3010
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: VAULT_API
              value: "http://{{ .Values.app.prefix }}-telemetry.{{ .Values.app.namespace }}.svc.cluster.local:8200"
        - name: {{ .Values.deployment.menubuildermanager.name }}-container
          imagePullPolicy: {{ .Values.deployment.customImagePullPolicy }}
          image: {{ .Values.deployment.menubuildermanager.image }}
          ports:
            - name: http-port
              containerPort: 3011
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: VAULT_API
              value: "http://{{ .Values.app.prefix }}-telemetry.{{ .Values.app.namespace }}.svc.cluster.local:8200"
        - name: {{ .Values.deployment.templatemanager.name }}-container
          imagePullPolicy: {{ .Values.deployment.customImagePullPolicy }}
          image: {{ .Values.deployment.templatemanager.image }}
          ports:
            - name: http-port
              containerPort: 3012
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: VAULT_API
              value: "http://{{ .Values.app.prefix }}-telemetry.{{ .Values.app.namespace }}.svc.cluster.local:8200"

