apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.prefix }}-desktop
  namespace: {{ .Values.app.namespace }}
spec:
  type: NodePort
  ports:
  - name: nginx-app
    port: {{ .Values.service.desktop.port }}
    targetPort: {{ .Values.service.desktop.targetPort }}
  selector:
    app: {{ .Values.app.prefix }}-desktop