/*
 * Template group angular_json
 * Compiled on Tue Mar 19 2019 11:15:15 GMT+0530 (India Standard Time)
 */
var path = require("path");
var base = path.dirname(module.filename);

function getInstance(st, group) {
    "use strict";
var r;
var gFile = "angular_json"; 

group.name = "angular_json";





//
// Template /angular_json
//
r = function(w, rc) {
    var g = this.owningGroup,
        s = this.scope;
    
    w.write("\n");
    w.write("{");
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\"$schema\": \"./node_modules/@angular/cli/lib/config/schema.json\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\"version\": 1,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\"newProjectRoot\": \"projects\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\"projects\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"");
    w.popIndentation();
    st.write(w, s, g, rc, s.projectname);
    w.write("\": {");
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"root\": \"\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"sourceRoot\": \"src\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"projectType\": \"application\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"prefix\": \"app\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"schematics\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"@schematics/angular:component\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"styleext\": \"scss\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"architect\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"build\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"builder\": \"@angular-devkit/build-angular:browser\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"options\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"outputPath\": \"dist/");
    w.popIndentation();
    st.write(w, s, g, rc, s.projectname);
    w.write("\",");
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"index\": \"src/index.html\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"main\": \"src/main.ts\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"polyfills\": \"src/polyfills.ts\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"tsConfig\": \"src/tsconfig.app.json\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"assets\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("\"src/favicon.ico\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("\"src/assets\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"styles\": [");
    w.popIndentation();
    w.write("\n");
    w.write("              ");
    if (st.test(s.cssArray)) {
    
        st.write(w, s, g, rc, (function() {
        var tp = [],
        attr = s.cssArray;
        tp.push(st.makeSubTemplate(g, function(w, rc) {
            var g = this.owningGroup,
            s = this.scope;
            
                     w.write("\"");
                     st.write(w, s, g, rc, s.name);
                     w.write("\",");
            }, [
            { name: "name"     }
            ])); 
        return st.map(attr, tp);
        })(), {separator: "\n"});
    
    
    }
    w.write("\n");
    w.pushIndentation("              ");
    w.write("\"src/styles.scss\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"scripts\": [");
    w.popIndentation();
    w.write("\n");
    w.write("               ");
    if (st.test(s.scriptArray)) {
    
        st.write(w, s, g, rc, (function() {
        var tp = [],
        attr = s.scriptArray;
        tp.push(st.makeSubTemplate(g, function(w, rc) {
            var g = this.owningGroup,
            s = this.scope;
            
                     w.write("\"");
                     st.write(w, s, g, rc, s.name);
                     w.write("\",");
            }, [
            { name: "name"     }
            ])); 
        return st.map(attr, tp);
        })(), {separator: "\n"});
    
    
    }
    w.write("\n");
    w.pushIndentation("            ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"configurations\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"production\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("\"fileReplacements\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("                ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("                  ");
    w.write("\"replace\": \"src/environments/environment.ts\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("                  ");
    w.write("\"with\": \"src/environments/environment.prod.ts\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("                ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("\"optimization\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("\"outputHashing\": \"all\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("\"sourceMap\": false,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("\"extractCss\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("\"namedChunks\": false,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("\"aot\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("\"extractLicenses\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("\"vendorChunk\": false,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("\"buildOptimizer\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("\"budgets\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("                ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("                  ");
    w.write("\"type\": \"initial\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("                  ");
    w.write("\"maximumWarning\": \"2mb\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("                  ");
    w.write("\"maximumError\": \"5mb\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("                ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"serve\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"builder\": \"@angular-devkit/build-angular:dev-server\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"options\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"browserTarget\": \"");
    w.popIndentation();
    st.write(w, s, g, rc, s.projectname);
    w.write(":build\"");
    w.write("\n");
    w.pushIndentation("          ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"configurations\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"production\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("\"browserTarget\": \"");
    w.popIndentation();
    st.write(w, s, g, rc, s.projectname);
    w.write(":build:production\"");
    w.write("\n");
    w.pushIndentation("            ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"extract-i18n\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"builder\": \"@angular-devkit/build-angular:extract-i18n\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"options\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"browserTarget\": \"");
    w.popIndentation();
    st.write(w, s, g, rc, s.projectname);
    w.write(":build\"");
    w.write("\n");
    w.pushIndentation("          ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"test\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"builder\": \"@angular-devkit/build-angular:karma\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"options\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"main\": \"src/test.ts\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"polyfills\": \"src/polyfills.ts\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"tsConfig\": \"src/tsconfig.spec.json\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"karmaConfig\": \"src/karma.conf.js\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"styles\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("\"src/styles.scss\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"scripts\": [],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"assets\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("\"src/favicon.ico\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("\"src/assets\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"lint\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"builder\": \"@angular-devkit/build-angular:tslint\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"options\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"tsConfig\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("\"src/tsconfig.app.json\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("\"src/tsconfig.spec.json\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"exclude\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("\"**/node_modules/**\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"");
    w.popIndentation();
    st.write(w, s, g, rc, s.projectname);
    w.write("-e2e\": {");
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"root\": \"e2e/\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"projectType\": \"application\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"prefix\": \"\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"architect\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"e2e\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"builder\": \"@angular-devkit/build-angular:protractor\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"options\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"protractorConfig\": \"e2e/protractor.conf.js\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"devServerTarget\": \"");
    w.popIndentation();
    st.write(w, s, g, rc, s.projectname);
    w.write(":serve\"");
    w.write("\n");
    w.pushIndentation("          ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"configurations\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"production\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("\"devServerTarget\": \"");
    w.popIndentation();
    st.write(w, s, g, rc, s.projectname);
    w.write(":serve:production\"");
    w.write("\n");
    w.pushIndentation("            ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"lint\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"builder\": \"@angular-devkit/build-angular:tslint\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"options\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"tsConfig\": \"e2e/tsconfig.e2e.json\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("\"exclude\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("              ");
    w.write("\"**/node_modules/**\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("            ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\"defaultProject\": \"");
    w.popIndentation();
    st.write(w, s, g, rc, s.projectname);
    w.write("\"");
    w.write("\n");
    w.write("}");
    w.write("\n");
};
r.args = [
        { name: "projectname"     },
{ name: "cssArray"     },
{ name: "scriptArray"     }
];
group.addTemplate("/angular_json", r); 


return group;
}
getInstance.base = base;

module.exports = getInstance;