/*
 * Template group tslint_json
 * Compiled on Thu Mar 14 2019 15:12:06 GMT+0530 (India Standard Time)
 */
var path = require("path");
var base = path.dirname(module.filename);

function getInstance(st, group) {
    "use strict";
var r;
var gFile = "tslint_json"; 

group.name = "tslint_json";





//
// Template /tslint_json
//
r = function(w, rc) {
    var g = this.owningGroup,
        s = this.scope;
    
    w.write("\n");
    w.write("{");
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\"rulesDirectory\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"codelyzer\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("\"rules\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"arrow-return-shorthand\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"callable-types\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"class-name\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"comment-format\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"check-space\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"curly\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"deprecation\": {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"severity\": \"warn\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("},");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"eofline\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"forin\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"import-blacklist\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"rxjs/Rx\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"import-spacing\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"indent\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"spaces\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"interface-over-type-literal\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"label-position\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"max-line-length\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("140");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"member-access\": false,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"member-ordering\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"order\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"static-field\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"instance-field\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"static-method\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("          ");
    w.write("\"instance-method\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("]");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"no-arg\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"no-bitwise\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"no-console\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"debug\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"info\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"time\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"timeEnd\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"trace\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"no-construct\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"no-debugger\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"no-duplicate-super\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"no-empty\": false,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"no-empty-interface\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"no-eval\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"no-inferrable-types\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"ignore-params\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"no-misused-new\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"no-non-null-assertion\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"no-redundant-jsdoc\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"no-shadowed-variable\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"no-string-literal\": false,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"no-string-throw\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"no-switch-case-fall-through\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"no-trailing-whitespace\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"no-unnecessary-initializer\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"no-unused-expression\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"no-use-before-declare\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"no-var-keyword\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"object-literal-sort-keys\": false,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"one-line\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"check-open-brace\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"check-catch\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"check-else\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"check-whitespace\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"prefer-const\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"quotemark\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"single\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"radix\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"semicolon\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"always\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"triple-equals\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"allow-null-check\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"typedef-whitespace\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("{");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"call-signature\": \"nospace\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"index-signature\": \"nospace\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"parameter\": \"nospace\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"property-declaration\": \"nospace\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("\"variable-declaration\": \"nospace\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"unified-signatures\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"variable-name\": false,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"whitespace\": [");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"check-branch\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"check-decl\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"check-operator\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"check-separator\",");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("\"check-type\"");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("],");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"no-output-on-prefix\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"use-input-property-decorator\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"use-output-property-decorator\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"use-host-property-decorator\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"no-input-rename\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"no-output-rename\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"use-life-cycle-interface\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"use-pipe-transform-interface\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"component-class-suffix\": true,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("\"directive-class-suffix\": true");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.write("}");
    w.write("\n");
    w.write("\n");
};
r.args = [
        
];
group.addTemplate("/tslint_json", r); 


return group;
}
getInstance.base = base;

module.exports = getInstance;