apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.prefix }}-generator
  namespace: {{ .Values.app.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: generation-manager
    port: 5000
    targetPort: 5000
    nodePort: 30500 
  - name: configuration-manager
    port: 5001
    targetPort: 5001
    nodePort: 30501
  - name: redis-container
    port: 6379
    targetPort: 6379
    nodePort: 30379
  - name: deployment-manager
    port: 5005
    targetPort: 5005
    nodePort: 30505
  - name: build-manager
    port: 5006
    targetPort: 5006
    nodePort: 30506
  - name: codegen-manager
    port: 5008
    targetPort: 5008
    nodePort: 30508
  - name: backendgen-manager
    port: 5009
    targetPort: 5009
    nodePort: 30509
  - name: datastore-manager
    port: 5010
    targetPort: 5010
    nodePort: 30510
  - name: mongo-manager
    port: 5011
    targetPort: 5011
    nodePort: 30511
  - name: nodegen-manager
    port: 5012
    targetPort: 5012
    nodePort: 30512

  selector:
    app: {{ .Values.app.prefix }}-generator

