apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.prefix }}-app
  namespace: {{ .Values.app.namespace }}
spec:
  type: NodePort
  ports:
  - name: flowmanager
    port: 3001
    targetPort: 3001
    nodePort: 30001
  - name: microflowmanager
    port: 3002
    targetPort: 3002
    nodePort: 30002
  - name: projectmanager
    port: 3003
    targetPort: 3003
    nodePort: 30003
  - name: screenmanager
    port: 3004
    targetPort: 3004
    nodePort: 30004
  - name: entitymanager
    port: 3005
    targetPort: 3005
    nodePort: 30005 
  - name: featuremanager
    port: 3006
    targetPort: 3006
    nodePort: 30006
  - name: securitymanager
    port: 3007
    targetPort: 3007
    nodePort: 30007
  - name: camundamanager
    port: 3008
    targetPort: 3008
    nodePort: 30008
  - name: proxymanager
    port: 3009
    targetPort: 3009
    nodePort: 30009
  - name: adminmanager
    port: 3010
    targetPort: 3010
    nodePort: 30010
  - name: menubuildermanager
    port: 3011
    targetPort: 3011
    nodePort: 30011
  - name: templatemanager
    port: 3012
    targetPort: 3012
    nodePort: 30012
  selector:
    app: {{ .Values.app.prefix }}-app
