kind: PersistentVolume
apiVersion: v1
metadata:
  name: gep-dev-generated-code-pv
  namespace: gep-dev-201902
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /geppetto/generated-code/
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gep-dev-generated-code-pvc
  namespace: gep-dev-201902
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
