apiVersion: v1
kind: Service
metadata:
  name: gep-dev-app
  namespace: gep-dev-201902
spec:
  type: NodePort
  ports:
  - name: flowmanager
    port: 3001
    targetPort: 3001
  - name: microflowmanager
    port: 3002
    targetPort: 3002
  - name: projectmanager
    port: 3003
    targetPort: 3003
  - name: screenmanager
    port: 3004
    targetPort: 3004
  - name: entitymanager
    port: 3005
    targetPort: 3005 
  - name: featuremanager
    port: 3006
    targetPort: 3006
  - name: featureflowmanager
    port: 3007
    targetPort: 3007
  - name: securitymanager
    port: 3008
    targetPort: 3008
  - name: camundamanager
    port: 3009
    targetPort: 3009
  - name: proxymanager
    port: 3010
    targetPort: 3010
  selector:
    app: gep-dev-app
