kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: gep-dev-logging
  labels:
    app: elasticsearch
spec:
  type: NodePort
  selector:
    app: elasticsearch
  ports:
    - name: rest
      port: 9200
    - name: inter-node
      port: 9300
    - name: kibana
      port: 5601
