kind: PersistentVolume
apiVersion: v1
metadata:
  name: gep-dev-elasticsearch-data-pv
  labels:
    type: local
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/elasticsearch/