/*
 * Template group polyfills_ts
 * Compiled on Fri Mar 15 2019 10:59:52 GMT+0530 (India Standard Time)
 */
var path = require("path");
var base = path.dirname(module.filename);

function getInstance(st, group) {
    "use strict";
var r;
var gFile = "polyfills_ts"; 

group.name = "polyfills_ts";





//
// Template /polyfills_ts
//
r = function(w, rc) {
    var g = this.owningGroup,
        s = this.scope;
    
    w.write("/**");
    w.write("\n");
    w.pushIndentation(" ");
    w.write("* This file includes polyfills needed by Angular and is loaded before the app.");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("* You can add your own extra polyfills to this file.");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("*");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("* This file is divided into 2 sections:");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("*   1. Browser polyfills. These are applied before loading ZoneJS and are sorted by browsers.");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("*   2. Application imports. Files imported after ZoneJS that should be loaded before your main");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("*      file.");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("*");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("* The current setup is for so-called \"evergreen\" browsers; the last versions of browsers that");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("* automatically update themselves. This includes Safari >= 10, Chrome >= 55 (including Opera),");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("* Edge >= 13 on the desktop, and iOS 10 and Chrome on mobile.");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("*");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("* Learn more in https://angular.io/guide/browser-support");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("*/");
    w.popIndentation();
    w.write("\n");
    w.write("\n");
    w.write("/***************************************************************************************************");
    w.write("\n");
    w.pushIndentation(" ");
    w.write("* BROWSER POLYFILLS");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("*/");
    w.popIndentation();
    w.write("\n");
    w.write("\n");
    w.write("/** IE9, IE10, IE11, and Chrome <55 requires all of the following polyfills.");
    w.write("\n");
    w.pushIndentation(" ");
    w.write("*  This also includes Android Emulators with older versions of Chrome and Google Search/Googlebot");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("*/");
    w.popIndentation();
    w.write("\n");
    w.write("\n");
    w.write("// import 'core-js/es6/symbol';");
    w.write("\n");
    w.write("// import 'core-js/es6/object';");
    w.write("\n");
    w.write("// import 'core-js/es6/function';");
    w.write("\n");
    w.write("// import 'core-js/es6/parse-int';");
    w.write("\n");
    w.write("// import 'core-js/es6/parse-float';");
    w.write("\n");
    w.write("// import 'core-js/es6/number';");
    w.write("\n");
    w.write("// import 'core-js/es6/math';");
    w.write("\n");
    w.write("// import 'core-js/es6/string';");
    w.write("\n");
    w.write("// import 'core-js/es6/date';");
    w.write("\n");
    w.write("// import 'core-js/es6/array';");
    w.write("\n");
    w.write("// import 'core-js/es6/regexp';");
    w.write("\n");
    w.write("// import 'core-js/es6/map';");
    w.write("\n");
    w.write("// import 'core-js/es6/weak-map';");
    w.write("\n");
    w.write("// import 'core-js/es6/set';");
    w.write("\n");
    w.write("\n");
    w.write("/** IE10 and IE11 requires the following for NgClass support on SVG elements */");
    w.write("\n");
    w.write("// import 'classlist.js';  // Run `npm install --save classlist.js`.");
    w.write("\n");
    w.write("\n");
    w.write("/** IE10 and IE11 requires the following for the Reflect API. */");
    w.write("\n");
    w.write("// import 'core-js/es6/reflect';");
    w.write("\n");
    w.write("\n");
    w.write("/**");
    w.write("\n");
    w.pushIndentation(" ");
    w.write("* Web Animations `@angular/platform-browser/animations`");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("* Only required if AnimationBuilder is used within the application and using IE/Edge or Safari.");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("* Standard animation support in Angular DOES NOT require any polyfills (as of Angular 6.0).");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("*/");
    w.popIndentation();
    w.write("\n");
    w.write("// import 'web-animations-js';  // Run `npm install --save web-animations-js`.");
    w.write("\n");
    w.write("\n");
    w.write("/**");
    w.write("\n");
    w.pushIndentation(" ");
    w.write("* By default, zone.js will patch all possible macroTask and DomEvents");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("* user can disable parts of macroTask/DomEvents patch by setting following flags");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("* because those flags need to be set before `zone.js` being loaded, and webpack");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("* will put import in the top of bundle, so user need to create a separate file");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("* in this directory (for example: zone-flags.ts), and put the following flags");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("* into that file, and then add the following code before importing zone.js.");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("* import './zone-flags.ts';");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("*");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("* The flags allowed in zone-flags.ts are listed here.");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("*");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("* The following flags will work for all browsers.");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("*");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("* (window as any).__Zone_disable_requestAnimationFrame = true; // disable patch requestAnimationFrame");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("* (window as any).__Zone_disable_on_property = true; // disable patch onProperty such as onclick");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("* (window as any).__zone_symbol__BLACK_LISTED_EVENTS = ['scroll', 'mousemove']; // disable patch specified eventNames");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("*");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("*  in IE/Edge developer tools, the addEventListener will also be wrapped by zone.js");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("*  with the following flag, it will bypass `zone.js` patch for IE/Edge");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("*");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("*  (window as any).__Zone_enable_cross_context_check = true;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("*");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("*/");
    w.popIndentation();
    w.write("\n");
    w.write("\n");
    w.write("/***************************************************************************************************");
    w.write("\n");
    w.pushIndentation(" ");
    w.write("* Zone JS is required by default for Angular itself.");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("*/");
    w.popIndentation();
    w.write("\n");
    w.write("import 'zone.js/dist/zone';  // Included with Angular CLI.");
    w.write("\n");
    w.write("\n");
    w.write("\n");
    w.write("/***************************************************************************************************");
    w.write("\n");
    w.pushIndentation(" ");
    w.write("* APPLICATION IMPORTS");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation(" ");
    w.write("*/");
    w.popIndentation();
    w.write("\n");
};
r.args = [
        
];
group.addTemplate("/polyfills_ts", r); 


return group;
}
getInstance.base = base;

module.exports = getInstance;