kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.app.prefix }}-logging-elasticsearch-data-pv
  labels:
    type: local
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/elasticsearch/
