apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.prefix }}-app
  namespace: {{ .Values.app.namespace }}
spec:
  type: NodePort
  ports:
  - name: {{ .Values.service.flowmanager.name }}
    port: {{ .Values.service.flowmanager.port }}
    targetPort: {{ .Values.service.flowmanager.targetPort }}
    nodePort: {{ .Values.service.flowmanager.nodePort }}
  - name: {{ .Values.service.microflowmanager.name }}
    port: {{ .Values.service.microflowmanager.port }} 
    targetPort: {{ .Values.service.microflowmanager.targetPort }}
    nodePort: {{ .Values.service.microflowmanager.nodePort }}
  - name: {{ .Values.service.projectmanager.name }}
    port: {{ .Values.service.projectmanager.port }}
    targetPort: {{ .Values.service.projectmanager.targetPort }}
    nodePort: {{ .Values.service.projectmanager.nodePort }}
  - name: {{ .Values.service.screenmanager.name }}
    port: {{ .Values.service.screenmanager.port }} 
    targetPort: {{ .Values.service.screenmanager.targetPort }}
    nodePort: {{ .Values.service.screenmanager.nodePort }}
  - name: {{ .Values.service.entitymanager.name }}
    port: {{ .Values.service.entitymanager.port }}
    targetPort: {{ .Values.service.entitymanager.targetPort }}
    nodePort: {{ .Values.service.entitymanager.nodePort }} 
  - name: {{ .Values.service.featuremanager.name }}
    port: {{ .Values.service.featuremanager.port }} 
    targetPort: {{ .Values.service.featuremanager.targetPort }}
    nodePort: {{ .Values.service.featuremanager.nodePort }}
  - name: {{ .Values.service.securitymanager.name }}
    port: {{ .Values.service.securitymanager.port }} 
    targetPort: {{ .Values.service.securitymanager.targetPort }}
    nodePort: {{ .Values.service.securitymanager.nodePort }}
  - name: {{ .Values.service.camundamanager.name }}
    port: {{ .Values.service.camundamanager.port }} 
    targetPort: {{ .Values.service.camundamanager.targetPort }}
    nodePort: {{ .Values.service.camundamanager.nodePort }}
  - name: {{ .Values.service.proxymanager.name }}
    port: {{ .Values.service.proxymanager.port }} 
    targetPort: {{ .Values.service.proxymanager.targetPort }}
    nodePort: {{ .Values.service.proxymanager.nodePort }}
  - name: {{ .Values.service.adminmanager.name }}
    port: {{ .Values.service.adminmanager.port }} 
    targetPort: {{ .Values.service.adminmanager.targetPort }}
    nodePort: {{ .Values.service.adminmanager.nodePort }}
  - name: {{ .Values.service.menubuildermanager.name }}
    port: {{ .Values.service.menubuildermanager.port }} 
    targetPort: {{ .Values.service.menubuildermanager.targetPort }}
    nodePort: {{ .Values.service.menubuildermanager.nodePort }}
  - name: {{ .Values.service.templatemanager.name }}
    port: {{ .Values.service.templatemanager.port }} 
    targetPort: {{ .Values.service.templatemanager.targetPort }}
    nodePort: {{ .Values.service.templatemanager.nodePort }}
  selector:
    app: {{ .Values.app.prefix }}-app
