kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.app.prefix }}-ops-postgres-pv
  namespace: {{ .Values.app.namespace }}
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgresql/
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.app.prefix }}-ops-postgres-pvc
  namespace: {{ .Values.app.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
          
