# This is a basic workflow to help you get started with Actions

name: auto_deployements for geppetto dev env

on:
  push:
    branches:
      - dev
env:
  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  aws-region: us-east-1      
########### Jobs ###########
jobs:
  validation:
    runs-on: ubuntu-latest 
    outputs:
        instance_data_value: ${{ steps.ec2.outputs.INSTANCE_STATE }} 
        run_frontend_jobs: ${{ steps.frontend.outputs.ui}}
        run_backend_jobs: ${{ steps.Backend.outputs.backend }}
        container : ${{ steps.Backend.outputs.featuremanager }} 
                ${{ steps.Backend.outputs.entitymanager }} 
                ${{ steps.Backend.outputs.flowmanager }} 
                ${{ steps.Backend.outputs.microflowmanager }} 
                ${{ steps.Backend.outputs.menubuildermanager }}
                ${{ steps.Backend.outputs.screenmanager }} 
                ${{ steps.Backend.outputs.securitymanager }} 
                ${{ steps.Backend.outputs.camundasvc }} 
                ${{ steps.Backend.outputs.Authproxy }}
                ${{ steps.Backend.outputs.templatemanager }} 
                ${{ steps.Backend.outputs.apigateway }} 
                ${{ steps.Backend.outputs.projectmanager }} 
                ${{ steps.Backend.outputs.deletemanager }}
                ${{ steps.Backend.outputs.githubmanager }} 
                ${{ steps.Backend.outputs.screengenmanager }} 
                ${{ steps.Backend.outputs.mongogenmanager }}
                ${{ steps.Backend.outputs.admingenmanager }}
                ${{ steps.Backend.outputs.nodegenmanager }}
                ${{ steps.Backend.outputs.datastoremanager }} 
                ${{ steps.Backend.outputs.inframanager }} 
                ${{ steps.Backend.outputs.generationmanager }} 
                ${{ steps.Backend.outputs.frontgenmanager }}
                ${{ steps.Backend.outputs.backendgenmanager }} 
                ${{ steps.Backend.outputs.angulargenmanager }} 
                ${{ steps.Backend.outputs.angtemplatemanager }} 
                ${{ steps.Backend.outputs.reactgenmanager }}
                ${{ steps.Backend.outputs.configmanager }} 
                ${{ steps.Backend.outputs.authgenmanager }}
                ${{ steps.Backend.outputs.codegenmanager }} 
                ${{ steps.Backend.outputs.ionicmanager }} 
                ${{ steps.Backend.outputs.swaggergenmanager }}
    steps:
    - name: aws configuration
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.aws-access-key-id }}
        aws-secret-access-key: ${{ env. aws-secret-access-key}}
        aws-region: ${{env.aws-region}}
    - name: Instance State
      run: echo "::set-output name=INSTANCE_STATE::$(aws ec2 describe-instances --instance-ids i-082c02e8aa3853a62 | jq '.Reservations[].Instances[].State.Name')"
      id: ec2
    - name:  Status of Instance 
      run: |
          echo ${{ steps.ec2.outputs.INSTANCE_STATE }} 
    - uses: actions/checkout@v2
    - name: Check for changes
      id: diff
      run: |
        if [ $GITHUB_BASE_REF ]; then
          git fetch origin $GITHUB_BASE_REF --depth=1
          export FILE_DIFF=$( git diff --name-only origin/$GITHUB_BASE_REF $GITHUB_SHA )
          echo "Diff between origin/$GITHUB_BASE_REF and $GITHUB_SHA"
        else
          git fetch origin ${{ github.event.before }} --depth=1
          export FILE_DIFF=$( git diff --name-only ${{ github.event.before }} $GITHUB_SHA )
          echo "Diff between ${{ github.event.before }} and $GITHUB_SHA"
        fi
        echo "$FILE_DIFF"
        echo "::set-output name=diff::$( echo "$FILE_DIFF" | sed ':a;N;$!ba;s/\n/%0A/g' )"
    - name: UI to build function
      id: frontend
      run: |
        FILE_DIFF="${{ steps.diff.outputs.diff }}"
        while read path;
        do
          directory="$( echo $path )"
          if [[ $directory != application/clients/desktop/* ]]; then
            echo "::set-output name=ui::notcommited" 
            continue
          else
            echo "::set-output name=ui::commited"
            break
          fi
        done <<< "$FILE_DIFF"
    - name: Backend function to build
      if: steps.ec2.outputs.INSTANCE_STATE == '"running"'
      id: Backend
      run: |
        FILE_DIFF="${{ steps.diff.outputs.diff }}"
        while read path;
        do
          directory="$( echo $path )"
          if [[ $directory == application/services/featuremanager/* ]]; then
              echo "::set-output name=backend::commited" 
              echo "::set-output name=featuremanager::featuremanager"
              continue
          elif [[ $directory == application/services/entitymanager/* ]]; then
            echo "::set-output name=backend::commited" 
            echo "::set-output name=entitymanager::entitymanager"
            continue
          elif [[ $directory == application/services/flowmanager/* ]]; then
            echo "::set-output name=backend::commited" 
            echo "::set-output name=flowmanager::flowmanager"
            continue
          elif [[ $directory == application/services/microflowmanager/* ]]; then
            echo "::set-output name=backend::commited" 
            echo "::set-output name=microflowmanager::microflowmanager"
            continue
          elif [[ $directory == application/services/menubuildermanager/* ]]; then
            echo "::set-output name=backend::commited" 
            echo "::set-output name=menubuildermanager::menubuildermanager"
            continue
          elif [[ $directory == application/services/screenmanager/* ]]; then
            echo "::set-output name=backend::commited" 
            echo "::set-output name=screenmanager::screenmanager"
            continue
          elif [[ $directory == application/services/securitymanager/* ]]; then
            echo "::set-output name=backend::commited" 
            echo "::set-output name=securitymanager::securitymanager"
            continue
          elif [[ $directory == application/services/Camunda/* ]]; then
            echo "::set-output name=backend::commited" 
            echo "::set-output name=camundasvc::camundasvc"
            continue
          elif [[ $directory == application/services/Auth-Proxy/* ]]; then
            echo "::set-output name=backend::commited" 
            echo "::set-output name=Authproxy::authproxy"
            continue
          elif [[ $directory == application/services/templatemanager/* ]]; then
            echo "::set-output name=backend::commited" 
            echo "::set-output name=templatemanager::templatemanager"
            continue
          elif [[ $directory == application/services/apigateway/* ]]; then
            echo "::set-output name=backend::commited"
            echo "::set-output name=apigateway::apigateway" 
            continue
          elif [[ $directory == application/services/projectmanager/* ]]; then
            echo "::set-output name=backend::commited" 
            echo "::set-output name=projectmanager::projectmanager"
            continue
          elif [[ $directory == application/services/deletemanager/* ]]; then
            echo "::set-output name=backend::commited" 
            echo "::set-output name=deletemanager::deletemanager"
            continue
          elif [[ $directory == generator/services/github-manager/* ]]; then
            echo "::set-output name=backend::commited"
            echo "::set-output name=githubmanager::githubmanager" 
            continue
          elif [[ $directory == generator/services/screen-gen-manager/* ]]; then
            echo "::set-output name=backend::commited"
            echo "::set-output name=screengenmanager::screengenmanager" 
            continue
          elif [[ $directory == generator/services/mongo-gen-manager/* ]]; then
            echo "::set-output name=backend::commited"
            echo "::set-output name=mongogenmanager::mongogenmanager" 
            continue
          elif [[ $directory == generator/services/Admin-manager/* ]]; then
            echo "::set-output name=backend::commited"
            echo "::set-output name=admingenmanager::admingenmanager" 
            continue
          elif [[ $directory == generator/services/node-gen-manager/* ]]; then
            echo "::set-output name=backend::commited"
            echo "::set-output name=nodegenmanager::nodegenmanager" 
            continue
          elif [[ $directory == generator/services/datastore-manager/* ]]; then
            echo "::set-output name=backend::commited"
            echo "::set-output name=datastoremanager::datastoremanager" 
            continue
          elif [[ $directory == generator/services/infrastructure-manager/* ]]; then
            echo "::set-output name=backend::commited"
            echo "::set-output name=inframanager::inframanager" 
            continue
          elif [[ $directory == generator/services/generation-manager/* ]]; then
            echo "::set-output name=backend::commited"
            echo "::set-output name=generationmanager::generationmanager" 
            continue
          elif [[ $directory == generator/services/frontend-gen-manager/* ]]; then
            echo "::set-output name=backend::commited"
            echo "::set-output name=frontgenmanager::frontgenmanager" 
            continue
          elif [[ $directory == generator/services/backend-gen-manager/* ]]; then
            echo "::set-output name=backend::commited"
            echo "::set-output name=backendgenmanager::backendgenmanager" 
            continue
          elif [[ $directory == generator/services/angular-gen-manager/* ]]; then
            echo "::set-output name=backend::commited"
            echo "::set-output name=angulargenmanager::angulargenmanager" 
            continue
          elif [[ $directory == generator/services/angular-template-manager/* ]]; then
            echo "::set-output name=backend::commited"
            echo "::set-output name=angtemplatemanager::angtemplatemanager" 
            continue
          elif [[ $directory == generator/services/reactv16-gen-manager/* ]]; then
            echo "::set-output name=backend::commited"
            echo "::set-output name=reactgenmanager::reactgenmanager" 
            continue
          elif [[ $directory == generator/services/configurationmanager/* ]]; then
            echo "::set-output name=backend::commited"
            echo "::set-output name=configmanager::configmanager" 
            continue
          elif [[ $directory == generator/services/auth-gen-manager/* ]]; then
            echo "::set-output name=backend::commited"
            echo "::set-output name=authgenmanager::authgenmanager" 
            continue
          elif [[ $directory == generator/services/code-gen-manager/* ]]; then
            echo "::set-output name=backend::commited"
            echo "::set-output name=codegenmanager::codegenmanager" 
            continue
          elif [[ $directory == generator/services/ionic-manager/* ]]; then
            echo "::set-output name=backend::commited"
            echo "::set-output name=ionicmanager::ionicmanager" 
            continue
          elif [[ $directory == generator/services/swagger-gen-manager/* ]]; then
            echo "::set-output name=backend::commited"
            echo "::set-output name=swaggergenmanager::swaggergenmanager" 
            continue
          else
            echo "::set-output name=backend::notcommited"
          fi
        done <<< "$FILE_DIFF"
  Upload build notes:
    needs: validation
    if: needs.validation.outputs.INSTANCE_STATE == '"running"'
    runs-on: ubuntu-latest
    steps:
      - name: Date
        run: echo "::set-output name=DATE_NOW::$(date +'%d/%m/%Y')"
        id: date  
      - name: Check the date
        run: |
          echo ${{ steps.date.outputs.DATE_NOW }}
      - uses: actions/checkout@v2
        with: 
          path: './'
      - name: Alpha value
        run: echo "::set-output name=ALPHA_NO::$(cat ./generator/services/configurationmanager/src/assests/configuration.json | jq -r '.base_config[0].value')"
        id: alpha
      - name: Check alpha
        run: echo ${{ steps.alpha.outputs.ALPHA_NO }}
      - name: Split Alpha
        uses: xom9ikk/split@v1
        id: split1
        with:
          string: ${{ steps.alpha.outputs.ALPHA_NO }}
          separator: '-'
          limit: -1
      - name: Split action
        uses: xom9ikk/split@v1
        with:
          major: ${{ steps.split1.outputs._0 }}
          minor: ${{ steps.split1.outputs._1 }}
      - name: Alpha_Split Output
        run: echo "::set-output name=SPLIT_ALPHA::$(( ${{ steps.split1.outputs._1 }}+1 ))"
        id: splitalpha
      - name: Alpha number
        run: echo ${{ steps.splitalpha.outputs.SPLIT_ALPHA }}
      - name: Build version
        run: echo "::set-output name=JSON_NO::$(cat ./generator/services/configurationmanager/src/assests/configuration.json | jq -r '.base_config[1].value')"
        id: json
      - name: Check version
        run: echo ${{ steps.json.outputs.JSON_NO }}
      - name: Split version code
        uses: xom9ikk/split@v1
        id: split
        with:
          string: ${{ steps.json.outputs.JSON_NO }}
          separator: .
          limit: -1
      - name: Build_Version action
        uses: xom9ikk/split@v1
        with:
          major: ${{ steps.split.outputs._0 }}
          minor: ${{ steps.split.outputs._1 }}
          patch: ${{ steps.split.outputs._2 }}
      - name: Adding the version
        run: echo $(( ${{ steps.split.outputs._2 }}+1 ))
      - name: Adding output
        run: echo "::set-output name=SPLIT::$(( ${{ steps.split.outputs._2 }}+1 ))"
        id: splitno
      - name: Check no
        run: echo ${{ steps.splitno.outputs.SPLIT }}
      - uses: actions/checkout@v2
        with: 
          path: './'      
      - run: |          
          echo "jq '.base_config[0].value="${{ steps.split1.outputs._0 }}-${{ steps.splitalpha.outputs.SPLIT_ALPHA }}"' ./generator/services/configurationmanager/src/assests/configuration.json " > ./generator/services/configurationmanager/src/assests/configuration.json
          echo "jq '.base_config[1].value="${{ steps.split.outputs._0 }}.${{ steps.split.outputs._1 }}.${{ steps.splitno.outputs.SPLIT }}"' ./generator/services/configurationmanager/src/assests/configuration.json " > ./generator/services/configurationmanager/src/assests/configuration.json 
          echo "jq '.base_config[2].value="${{ steps.date.outputs.DATE_NOW }}"' ./generator/services/configurationmanager/src/assests/configuration.json " > ./generator/services/configurationmanager/src/assests/configuration.json
     
      - uses: EndBug/add-and-commit@v6
        with:
          message: 'Add the version and date'
          add: './generator/services/configurationmanager/src/assests/configuration.json --force'
          cwd: './' 
          token: ${{ secrets.BUILDVERSION_BUILDDATE }}      
  login:
    needs: validation
    if: needs.validation.outputs.run_backend_jobs == 'commited'
    runs-on: ubuntu-latest
    steps:
    - name: Update the apt-get & install the sshpass
      run: sudo apt-get update && sudo apt-get -y install openssh-client && sudo apt-get -y install sshpass 
    - name: Login into the dev instance by using SSH
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: 'ubuntu@ec2-34-197-46-177.compute-1.amazonaws.com'
        privateKey: ${{ secrets.PRIVATE_KEY }}
        command: |
          cd geppettotest
          git pull git@github.com:dan-castillo/geppettotest.git
          cd devops/docker-compose
          docker-compose down
          docker rmi ${{ needs.validate.outputs.container }}
          echo "Backend Deploying..."
          docker-compose up -d --build
          sleep 50
          curl -i -X POST -H "Content-Type: multipart/form-data" -F "data=@../../application/services/Camunda/Gep_authorize.dmn" -F "deployment-name=gep_authorize" -F "enable-duplicate-filtering=true" -F "deploy-changed-only=true" http://localhost:8080/engine-rest/deployment/create
          echo "uploading the seed file....."
          sleep 30
          docker exec codegenmanager sh -c "mkdir /geppetto/generated-code; mkdir /geppetto/template;"
          sleep 20
          docker cp ../../generator/services/seed codegenmanager:/geppetto/template/
          echo "seed file copied"
          echo "Backend deployment completed"     
  Upload_S3:
    runs-on: ubuntu-latest
    needs: validation
    if: needs.validation.outputs.run_frontend_jobs == 'commited'
    steps:
    - name: Check the  branch
      uses: actions/checkout@v2
    - name: Installing the Node and its dependies
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Installing node modules
      working-directory: ./application/clients/desktop
      run: |
        npm install -g @angular/cli
        npm i node-sass@4.8.3
        npm i 
        ng build --configuration=devops
    - name: Uploaging dist files into the S3 bucket
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: geppetto-dev
        AWS_ACCESS_KEY_ID: ${{ env.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ env. aws-secret-access-key}}
        SOURCE_DIR: "application/clients/desktop/dist/GeppettoBuilder"
