kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: {{ .Values.logging.namespace }}
  labels:
    app: elasticsearch
spec:
  type: {{ .Values.service.type }}
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      name: rest
      nodePort: 30092
    - port: 9300
      name: inter-node
      nodePort: 30093
